[package]
name = "mdict2sql"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
lazy_static = "1.5.0"
once_cell = "1.19.0"
regex = "1.10.5"
rusqlite = "0.31.0"
tklog = "0.0.8"
mdict-parser = { path = "./mdict-parser" }
num_cpus = "1.16.0"
